os: Visual Studio 2015
 
environment:
  matrix:
    - BUILD_PROFILE: ci_part1
    - BUILD_PROFILE: ci_part2

init:
  - git config --global core.autocrlf true

build_script: 
  - cmd: build.cmd %BUILD_PROFILE%

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  # The newest version of MSBuild installed will overwrite the older ones.
  - set PATH=%ProgramFiles(x86)%\MSBuild\12.0\Bin;%PATH%
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%
  - set PATH=%ProgramFiles(x86)%\MSBuild\15.0\Bin;%PATH%

test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Release
    name: Release
  - path: tests\TestResults
    name: TestResults
    type: zip

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))